"""add_max_team_members_to_hackathons

Revision ID: 290d08356122
Revises: 6261869ca849
Create Date: 2026-07-05 01:53:24.132695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '290d08356122'
down_revision: Union[str, None] = '6261869ca849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackathons', sa.Column('max_team_members', sa.Integer(), server_default='5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hackathons', 'max_team_members')
    # ### end Alembic commands ###
