"""add_created_by_to_questions

Revision ID: 3a7e7585462c
Revises: ec8a22cf292d
Create Date: 2026-04-22 13:55:24.270270

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a7e7585462c"
down_revision: str | None = "ec8a22cf292d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("questions", sa.Column("created_by", sa.Integer(), nullable=True))
    op.execute("UPDATE questions SET created_by = 1")
    op.alter_column("questions", "created_by", nullable=False)
    op.create_index(op.f("ix_questions_created_by"), "questions", ["created_by"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_questions_created_by"), table_name="questions")
    op.drop_column("questions", "created_by")
    # ### end Alembic commands ###
