"""add_show_answers_and_hackathon_registrations

Revision ID: 6261869ca849
Revises: 6c2f7de1a9ab
Create Date: 2026-07-05 01:41:42.324384

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6261869ca849'
down_revision: str | None = '6c2f7de1a9ab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hackathon_teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hackathon_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('leader_id', sa.Integer(), nullable=False),
    sa.Column('member_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hackathon_teams_code'), 'hackathon_teams', ['code'], unique=True)
    op.create_index(op.f('ix_hackathon_teams_hackathon_id'), 'hackathon_teams', ['hackathon_id'], unique=False)
    op.create_table('hackathon_registrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hackathon_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='registration_status_enum'), server_default='pending', nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['hackathon_teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hackathon_registrations_hackathon_id'), 'hackathon_registrations', ['hackathon_id'], unique=False)
    op.create_index(op.f('ix_hackathon_registrations_team_id'), 'hackathon_registrations', ['team_id'], unique=False)
    op.create_index(op.f('ix_hackathon_registrations_user_id'), 'hackathon_registrations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hackathon_registrations_user_id'), table_name='hackathon_registrations')
    op.drop_index(op.f('ix_hackathon_registrations_team_id'), table_name='hackathon_registrations')
    op.drop_index(op.f('ix_hackathon_registrations_hackathon_id'), table_name='hackathon_registrations')
    op.drop_table('hackathon_registrations')
    op.drop_index(op.f('ix_hackathon_teams_hackathon_id'), table_name='hackathon_teams')
    op.drop_index(op.f('ix_hackathon_teams_code'), table_name='hackathon_teams')
    op.drop_table('hackathon_teams')
    # ### end Alembic commands ###
