"""create_hackathon_submissions_table

Revision ID: 68143e5f03a6
Revises: 290d08356122
Create Date: 2026-07-06 10:50:10.404922

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '68143e5f03a6'
down_revision: str | None = '290d08356122'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hackathon_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('script_url', sa.Text(), nullable=False),
    sa.Column('model_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADING', 'EXTRACTING', 'RUNNING', 'EVALUATING', 'PUBLISHED', 'FAILED', 'CANCELLED', name='submission_status_enum'), server_default='UPLOADING', nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['hackathon_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['hackathon_teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hackathon_submissions_task_id'), 'hackathon_submissions', ['task_id'], unique=False)
    op.create_index(op.f('ix_hackathon_submissions_team_id'), 'hackathon_submissions', ['team_id'], unique=False)
    op.create_index(op.f('ix_hackathon_submissions_user_id'), 'hackathon_submissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hackathon_submissions_user_id'), table_name='hackathon_submissions')
    op.drop_index(op.f('ix_hackathon_submissions_team_id'), table_name='hackathon_submissions')
    op.drop_index(op.f('ix_hackathon_submissions_task_id'), table_name='hackathon_submissions')
    op.drop_table('hackathon_submissions')
    # ### end Alembic commands ###
