"""add_show_answers_to_exams

Revision ID: 7fda307f1a07
Revises: e88afa090f4e
Create Date: 2026-07-07 00:02:46.137179

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7fda307f1a07'
down_revision: str | None = 'e88afa090f4e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('show_answers', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'show_answers')
    # ### end Alembic commands ###
