"""add_created_at_and_updated_at_to_hackathons

Revision ID: 8e800767ffdc
Revises: a03acd51f319
Create Date: 2026-07-03 00:37:37.604515

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "8e800767ffdc"
down_revision: str | None = "a03acd51f319"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
