"""add_created_at_and_updated_at_to_hackathons

Revision ID: 8e800767ffdc
Revises: a03acd51f319
Create Date: 2026-07-03 00:37:37.604515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e800767ffdc'
down_revision: Union[str, None] = 'a03acd51f319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
