"""add inference_time and public_score

Revision ID: 90d96481779d
Revises: 7fda307f1a07
Create Date: 2026-07-10 11:30:41.918923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90d96481779d'
down_revision: Union[str, None] = '7fda307f1a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_hackathon_submissions_runtime_profile'), 'hackathon_submissions', type_='foreignkey')
    op.drop_index(op.f('ix_hackathon_submissions_runtime_profile_id'), table_name='hackathon_submissions')
    op.drop_column('hackathon_submissions', 'runtime_profile_id')
    op.drop_column('hackathon_submissions', 'score')
    
    op.drop_index(op.f('ix_dependency_requests_created_at'), table_name='dependency_requests')
    op.drop_index(op.f('ix_dependency_requests_hackathon_id'), table_name='dependency_requests')
    op.drop_index(op.f('ix_dependency_requests_status'), table_name='dependency_requests')
    op.drop_index(op.f('ix_dependency_requests_task_id'), table_name='dependency_requests')
    op.drop_index(op.f('ix_dependency_requests_team_id'), table_name='dependency_requests')
    op.drop_index(op.f('ix_dependency_requests_user_id'), table_name='dependency_requests')
    op.drop_table('dependency_requests')
    op.drop_index(op.f('ix_runtime_profiles_is_active'), table_name='runtime_profiles')
    op.drop_index(op.f('ix_runtime_profiles_name'), table_name='runtime_profiles')
    op.drop_table('runtime_profiles')
    
    op.add_column('hackathon_submissions', sa.Column('public_score', sa.Float(), nullable=True))
    op.add_column('hackathon_submissions', sa.Column('private_score', sa.Float(), nullable=True))
    op.add_column('hackathon_submissions', sa.Column('inference_time', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackathon_submissions', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('hackathon_submissions', sa.Column('runtime_profile_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_hackathon_submissions_runtime_profile'), 'hackathon_submissions', 'runtime_profiles', ['runtime_profile_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_hackathon_submissions_runtime_profile_id'), 'hackathon_submissions', ['runtime_profile_id'], unique=False)
    op.drop_column('hackathon_submissions', 'inference_time')
    op.drop_column('hackathon_submissions', 'private_score')
    op.drop_column('hackathon_submissions', 'public_score')
    op.create_table('runtime_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('docker_image', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('docker_image_tag', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('python_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cuda_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('allowed_packages_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cpu_limit', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('2.0'), autoincrement=False, nullable=False),
    sa.Column('memory_limit_mb', sa.INTEGER(), server_default=sa.text('2048'), autoincrement=False, nullable=False),
    sa.Column('gpu_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('gpu_limit', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('timeout_seconds', sa.INTEGER(), server_default=sa.text('300'), autoincrement=False, nullable=False),
    sa.Column('pids_limit', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('runtime_profiles_pkey')),
    sa.UniqueConstraint('name', name=op.f('runtime_profiles_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_runtime_profiles_name'), 'runtime_profiles', ['name'], unique=False)
    op.create_index(op.f('ix_runtime_profiles_is_active'), 'runtime_profiles', ['is_active'], unique=False)
    op.create_table('dependency_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('hackathon_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('package_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('package_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='dependency_request_status_enum'), server_default=sa.text("'PENDING'::dependency_request_status_enum"), autoincrement=False, nullable=False),
    sa.Column('admin_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], name=op.f('dependency_requests_hackathon_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['hackathon_tasks.id'], name=op.f('dependency_requests_task_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['hackathon_teams.id'], name=op.f('dependency_requests_team_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('dependency_requests_pkey'))
    )
    op.create_index(op.f('ix_dependency_requests_user_id'), 'dependency_requests', ['user_id'], unique=False)
    op.create_index(op.f('ix_dependency_requests_team_id'), 'dependency_requests', ['team_id'], unique=False)
    op.create_index(op.f('ix_dependency_requests_task_id'), 'dependency_requests', ['task_id'], unique=False)
    op.create_index(op.f('ix_dependency_requests_status'), 'dependency_requests', ['status'], unique=False)
    op.create_index(op.f('ix_dependency_requests_hackathon_id'), 'dependency_requests', ['hackathon_id'], unique=False)
    op.create_index(op.f('ix_dependency_requests_created_at'), 'dependency_requests', ['created_at'], unique=False)
    # ### end Alembic commands ###
