"""add inference_time and public_score

Revision ID: 90d96481779d
Revises: 7fda307f1a07
Create Date: 2026-07-10 11:30:41.918923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90d96481779d'
down_revision: Union[str, None] = '7fda307f1a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hackathon_submissions', 'score')
    
    op.add_column('hackathon_submissions', sa.Column('public_score', sa.Float(), nullable=True))
    op.add_column('hackathon_submissions', sa.Column('private_score', sa.Float(), nullable=True))
    op.add_column('hackathon_submissions', sa.Column('inference_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackathon_submissions', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('hackathon_submissions', 'inference_time')
    op.drop_column('hackathon_submissions', 'private_score')
    op.drop_column('hackathon_submissions', 'public_score')
    # ### end Alembic commands ###
