"""add learning stage 1 fields

Revision ID: 9d5def7ecf64
Revises: a67e7585462d
Create Date: 2026-06-26 14:20:09.946269

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9d5def7ecf64"
down_revision: Union[str, None] = "a67e7585462d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lessons",
        sa.Column("content_md", sa.String(), server_default="", nullable=False),
    )
    op.drop_index(op.f("ix_lessons_order"), table_name="lessons", if_exists=True)
    op.add_column(
        "questions",
        sa.Column(
            "difficulty",
            sa.Enum("EASY", "MEDIUM", "HARD", name="difficulty"),
            server_default="EASY",
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_questions_difficulty"), "questions", ["difficulty"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_questions_difficulty"), table_name="questions")
    op.drop_column("questions", "difficulty")
    op.create_index(op.f("ix_lessons_order"), "lessons", ["order"], unique=False)
    op.drop_column("lessons", "content_md")
    # ### end Alembic commands ###
