"""remove_blog_id_and_content_md

Revision ID: 9f3a6b80b6ef
Revises: 0f3e2d1c4b5a
Create Date: 2026-07-02 01:03:50.391271

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9f3a6b80b6ef'
down_revision: str | None = '0f3e2d1c4b5a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'content_md')
    op.drop_column('lessons', 'blog_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('blog_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('lessons', sa.Column('content_md', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
