"""add_created_at_and_updated_at_to_hackathons

Revision ID: a03acd51f319
Revises: 0938a40e560d
Create Date: 2026-07-03 00:37:11.636307

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a03acd51f319'
down_revision: str | None = '0938a40e560d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackathons', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('hackathons', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hackathons', 'updated_at')
    op.drop_column('hackathons', 'created_at')
    # ### end Alembic commands ###
