"""add_lesson_id_to_questions

Revision ID: a32f98d14447
Revises: f608f5d3b897
Create Date: 2026-04-16 02:05:37.356129

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a32f98d14447'
down_revision: str | None = 'f608f5d3b897'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('lesson_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_questions_lesson_id'), 'questions', ['lesson_id'], unique=False)
    op.create_foreign_key(None, 'questions', 'lessons', ['lesson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_index(op.f('ix_questions_lesson_id'), table_name='questions')
    op.drop_column('questions', 'lesson_id')
    # ### end Alembic commands ###
