"""create_tags_table

Revision ID: a66a1656a354
Revises: 7fda307f1a07
Create Date: 2026-07-10 16:37:10.589280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a66a1656a354'
down_revision: Union[str, None] = '7fda307f1a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.add_column('hackathon_submissions', sa.Column('score', sa.Float(), nullable=True))
    op.drop_column('hackathon_submissions', 'public_score')
    op.drop_column('hackathon_submissions', 'private_score')
    op.drop_column('hackathon_submissions', 'inference_time')
    op.alter_column('questions', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=postgresql.ARRAY(sa.UUID()),
               existing_nullable=False,
               postgresql_using='tags::uuid[]')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'tags',
               existing_type=postgresql.ARRAY(sa.UUID()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=False,
               postgresql_using='tags::text[]')
    op.add_column('hackathon_submissions', sa.Column('inference_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('hackathon_submissions', sa.Column('private_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('hackathon_submissions', sa.Column('public_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('hackathon_submissions', 'score')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
