"""add slug and blog_id to lessons

Revision ID: b7a3e8c9d123
Revises: 9d5def7ecf64
Create Date: 2026-06-29 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b7a3e8c9d123'
down_revision: Union[str, None] = '9d5def7ecf64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('lessons', sa.Column('blog_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_lessons_slug'), 'lessons', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lessons_slug'), table_name='lessons')
    op.drop_column('lessons', 'blog_id')
    op.drop_column('lessons', 'slug')
    # ### end Alembic commands ###
