"""add_show_answers_to_exams

Revision ID: cc1812904cd2
Revises: 8e800767ffdc
Create Date: 2026-07-05 00:19:07.384760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc1812904cd2'
down_revision: Union[str, None] = '8e800767ffdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hackathon_tasks_hackathon_id'), table_name='hackathon_tasks')
    op.drop_table('hackathon_tasks')
    op.alter_column('exams', 'show_answers',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exams', 'show_answers',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_table('hackathon_tasks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('hackathon_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('problem_description_md', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('private_test_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('public_test_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metric_type', postgresql.ENUM('rmse', 'f1_score', 'accuracy', name='metric_type_enum'), autoincrement=False, nullable=False),
    sa.Column('max_submissions', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], name=op.f('hackathon_tasks_hackathon_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('hackathon_tasks_pkey'))
    )
    op.create_index(op.f('ix_hackathon_tasks_hackathon_id'), 'hackathon_tasks', ['hackathon_id'], unique=False)
    # ### end Alembic commands ###
