"""add lession

Revision ID: cf281fd6ea05
Revises: 4e4b87526a03
Create Date: 2026-04-16 00:44:59.152318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf281fd6ea05'
down_revision: Union[str, None] = '4e4b87526a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lessons_created_by'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_order'), table_name='lessons')
    op.drop_column('lessons', 'created_by')
    op.drop_index(op.f('ix_practice_sessions_lesson_id'), table_name='practice_sessions')
    op.drop_constraint(op.f('fk_practice_sessions_lesson_id'), 'practice_sessions', type_='foreignkey')
    op.drop_column('practice_sessions', 'lesson_id')
    op.drop_column('practice_sessions', 'lesson_ids_filter')
    op.drop_index(op.f('ix_questions_lesson_id'), table_name='questions')
    op.drop_constraint(op.f('fk_questions_lesson_id'), 'questions', type_='foreignkey')
    op.drop_column('questions', 'lesson_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('lesson_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_questions_lesson_id'), 'questions', 'lessons', ['lesson_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_questions_lesson_id'), 'questions', ['lesson_id'], unique=False)
    op.add_column('practice_sessions', sa.Column('lesson_ids_filter', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False))
    op.add_column('practice_sessions', sa.Column('lesson_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_practice_sessions_lesson_id'), 'practice_sessions', 'lessons', ['lesson_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_practice_sessions_lesson_id'), 'practice_sessions', ['lesson_id'], unique=False)
    op.add_column('lessons', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_lessons_order'), 'lessons', ['order'], unique=False)
    op.create_index(op.f('ix_lessons_created_by'), 'lessons', ['created_by'], unique=False)
    # ### end Alembic commands ###
