"""add lession

Revision ID: cf281fd6ea05
Revises: 4e4b87526a03
Create Date: 2026-04-16 00:44:59.152318

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf281fd6ea05"
down_revision: str | None = "4e4b87526a03"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # The original autogenerated migration was incorrect:
    # it tried to drop lesson-related columns/indexes, but the fresh database
    # does not even have the lessons table yet.
    #
    # This migration should create the lessons table because the next migration
    # a32f98d14447_add_lesson_id_to_questions.py adds questions.lesson_id
    # and creates a foreign key to lessons.id.

    op.create_table(
        "lessons",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False, server_default=""),
        sa.Column("order", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_lessons_order"),
        "lessons",
        ["order"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_lessons_order"), table_name="lessons")
    op.drop_table("lessons")
