"""create_modules_table_and_link_lessons

Revision ID: d7f1a3ed798a
Revises: 76eeb6322457
Create Date: 2026-07-14 14:50:43.042259

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d7f1a3ed798a"
down_revision: str | None = "76eeb6322457"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "modules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), server_default="", nullable=False),
        sa.Column("order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("lessons", sa.Column("module_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_lessons_module_id"), "lessons", ["module_id"], unique=False)
    op.create_foreign_key(None, "lessons", "modules", ["module_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "lessons", type_="foreignkey")
    op.drop_index(op.f("ix_lessons_module_id"), table_name="lessons")
    op.drop_column("lessons", "module_id")
    op.drop_table("modules")
    # ### end Alembic commands ###
