"""add participant_ids to exams

Revision ID: ec8a22cf292d
Revises: a32f98d14447
Create Date: 2026-04-16 05:18:29.947338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec8a22cf292d'
down_revision: Union[str, None] = 'a32f98d14447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('participant_ids', postgresql.ARRAY(sa.Integer()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'participant_ids')
    # ### end Alembic commands ###
