"""cascade_delete_questions_and_homeworks_on_lesson_delete

Revision ID: f2280fa41e46
Revises: e71b2a9c4d88
Create Date: 2026-09-26 20:53:22.811282

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2280fa41e46'
down_revision: Union[str, None] = 'e71b2a9c4d88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_homeworks_lesson_id'), 'homeworks', type_='foreignkey')
    op.create_foreign_key(None, 'homeworks', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.add_column('import_sessions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('import_sessions', 'file_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('import_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PROCESSING', 'COMPLETED', 'FAILED', name='importsessionstatus', native_enum=False, length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'PROCESSING'::character varying"))
    op.alter_column('import_sessions', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('import_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_import_sessions_status'), table_name='import_sessions')
    op.alter_column('lesson_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=False)
    op.alter_column('questions', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    op.alter_column('questions', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DRAFT', 'PUBLIC', name='questionstatus', native_enum=False, length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'PUBLIC'::character varying"))
    op.alter_column('questions', 'duplicate_status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('UNIQUE', 'NONE', 'POSSIBLE_DUPLICATE', 'EXACT_DUPLICATE', name='duplicatestatus', native_enum=False, length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'UNIQUE'::character varying"))
    op.alter_column('questions', 'review_locked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint(op.f('questions_lesson_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_lesson_id_fkey'), 'questions', 'lessons', ['lesson_id'], ['id'])
    op.alter_column('questions', 'review_locked_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('questions', 'duplicate_status',
               existing_type=sa.Enum('UNIQUE', 'NONE', 'POSSIBLE_DUPLICATE', 'EXACT_DUPLICATE', name='duplicatestatus', native_enum=False, length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'UNIQUE'::character varying"))
    op.alter_column('questions', 'status',
               existing_type=sa.Enum('DRAFT', 'PUBLIC', name='questionstatus', native_enum=False, length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'PUBLIC'::character varying"))
    op.alter_column('questions', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               existing_nullable=True)
    op.alter_column('lesson_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               existing_nullable=False)
    op.create_index(op.f('ix_import_sessions_status'), 'import_sessions', ['status'], unique=False)
    op.alter_column('import_sessions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('import_sessions', 'error_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('import_sessions', 'status',
               existing_type=sa.Enum('PROCESSING', 'COMPLETED', 'FAILED', name='importsessionstatus', native_enum=False, length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'PROCESSING'::character varying"))
    op.alter_column('import_sessions', 'file_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.drop_column('import_sessions', 'updated_at')
    op.drop_constraint(None, 'homeworks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_homeworks_lesson_id'), 'homeworks', 'lessons', ['lesson_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
