from __future__ import annotations

from typing import Protocol
from uuid import UUID

from app.domain.hackathon.models import CompetitionEntity, SubmissionEntity, TaskEntity


class CompetitionRepository(Protocol):
    async def list_all(self) -> list[CompetitionEntity]: ...

    async def get(self, competition_id: UUID) -> CompetitionEntity | None: ...

    async def add(self, entity: CompetitionEntity) -> CompetitionEntity: ...

    async def update(self, entity: CompetitionEntity) -> CompetitionEntity: ...

    async def delete(self, entity: CompetitionEntity) -> None: ...


class TaskRepository(Protocol):
    async def list_by_competition(self, competition_id: UUID) -> list[TaskEntity]: ...

    async def get(self, task_id: UUID) -> TaskEntity | None: ...

    async def add(self, entity: TaskEntity) -> TaskEntity: ...

    async def update(self, entity: TaskEntity) -> TaskEntity: ...

    async def delete(self, entity: TaskEntity) -> None: ...


class SubmissionRepository(Protocol):
    async def list_by_competition(self, competition_id: UUID) -> list[SubmissionEntity]: ...

    async def list_by_participant(self, competition_id: UUID, participant_id: int) -> list[SubmissionEntity]: ...

    async def get(self, submission_id: UUID) -> SubmissionEntity | None: ...

    async def add(self, entity: SubmissionEntity) -> SubmissionEntity: ...

    async def update(self, entity: SubmissionEntity) -> SubmissionEntity: ...

    async def count_successful_by_participant(self, competition_id: UUID, participant_id: int) -> int: ...

    async def latest_successful_by_participant(self, competition_id: UUID, participant_id: int) -> SubmissionEntity | None: ...
